### ISSUE TITLE
TypeError: Cannot read properties of undefined (reading 'getItem')

### ISSUE THREAD

**Issue by PrestonSam** [dopry/svelte-oidc#43]
A strange error that occurs even in fresh copies of SvelteKit.

Steps to reproduce:
```bash
npm create svelte@latest whynowork
# Skeleton project
# Yes use TypeScript syntax
# No additional features

cd whynowork
npm install
npm install @dopry/svelte-oid

vim src/routes/+page.svelte
# Copy snippet from README into source file, wrapping the code in the <script> tags and moving it to the top of the file
npm run dev

# Open in browser
```

Produces the following error in the terminal

```
TypeError: Cannot read properties of undefined (reading 'getItem')
    at t [as get] (/.../whynowork/node_modules/oidc-client/lib/oidc-client.min.js:1:15839)
    at e.t [as _loadUser] (/.../whynowork/node_modules/oidc-client/lib/oidc-client.min.js:49:24407)
    at e.t [as getUser] (/.../whynowork/node_modules/oidc-client/lib/oidc-client.min.js:49:10094)
    at t [as start] (/.../whynowork/node_modules/oidc-client/lib/oidc-client.min.js:49:42845)
    at e.t [as startSilentRenew] (/.../whynowork/node_modules/oidc-client/lib/oidc-client.min.js:49:24266)
    at new e (/.../whynowork/node_modules/oidc-client/lib/oidc-client.min.js:49:9450)
    at eval (/node_modules/@dopry/svelte-oidc/src/components/OidcContext.svelte:107:22)
    at Object.$$render (/node_modules/svelte/internal/index.mjs:2042:22)
    at eval (/src/routes/+page.svelte:47:94)
    at Object.$$render (/node_modules/svelte/internal/index.mjs:2042:22)
TypeError: Cannot read properties of undefined (reading 'getItem')
    at t [as get] (/.../whynowork/node_modules/oidc-client/lib/oidc-client.min.js:1:15839)
    at e.t [as _loadUser] (/.../whynowork/node_modules/oidc-client/lib/oidc-client.min.js:49:24407)
    at e.t [as getUser] (/.../whynowork/node_modules/oidc-client/lib/oidc-client.min.js:49:10094)
    at t [as start] (/.../whynowork/node_modules/oidc-client/lib/oidc-client.min.js:49:42845)
    at e.t [as startSilentRenew] (/.../whynowork/node_modules/oidc-client/lib/oidc-client.min.js:49:24266)
    at new e (/.../whynowork/node_modules/oidc-client/lib/oidc-client.min.js:49:9450)
    at eval (/node_modules/@dopry/svelte-oidc/src/components/OidcContext.svelte:107:22)
    at Object.$$render (/node_modules/svelte/internal/index.mjs:2042:22)
    at eval (/src/routes/+page.svelte:47:94)
    at Object.$$render (/node_modules/svelte/internal/index.mjs:2042:22)
```

**Comment by dopry** [comment]
It looks like you're trying to run client side only code on the server.  Did you remember the code from https://github.com/dopry/svelte-oidc#sveltekitssr

**Comment by PrestonSam** [comment]
Yes, you're completely right. I'm sorry for wasting your time 🤦
